version: "3"
services:
  nginx:
    image: ifintech/nginx-php
    ports:
      - "80:80"
    environment:
      APP_NAME: demo
    links:
      - demo_php

  demo_php:
    build: .
    command: php-fpm
    volumes:
      - .:/data1/htdocs/demo
    links:
      - demo_mysql
      - demo_redis

  demo_mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: Root1.pwd
      MYSQL_DATABASE: demo
    volumes:
      - ./build/sql:/docker-entrypoint-initdb.d

  demo_redis:
    image: redis:alpine